apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pprc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pprc
    app.kubernetes.io/part-of: byoc-app-zbyn
  name: pprc
spec:
  rules:
  - host: pprc-byoc-mmgs-tenant.apps.059e86bc4845c62f87b5.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: pprc
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
